apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv


spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-073a693f457cb00a4
    fsType: ext4
